# Generated by Django 4.2.5 on 2023-09-15 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField()),
                ('contact_no', models.CharField(max_length=15)),
                ('client_name', models.CharField(max_length=50)),
                ('delivery_address', models.CharField(max_length=150)),
                ('order_status', models.CharField(default='PENDING', max_length=15)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.menuitem')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_map', to='products.order')),
            ],
        ),
    ]
