# Generated by Django 4.2.5 on 2023-09-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. Usernames must be unique.', max_length=150, null=True, unique=True),
        ),
    ]
