# Generated by Django 4.2.5 on 2023-09-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
