# Generated by Django 4.2.5 on 2023-09-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
